### ISSUE TITLE
OSError: Encoding error 

### ISSUE THREAD

**Issue by Seaense** [holgern/pyedflib#120]
**"OSError: File S001R03.edf was found but can't be accessed. Make sure it contains no special characters or change your locale to use UTF"**
Am using the same file that you have used still getting the above error. And I have gone through the [locale error](https://github.com/holgern/pyedflib/issues/115)  still can't rectify the issue. Need some clear picture about it

**Comment by skjerns** [comment]
- Which OS are you on and which version of `pyedflib` do you have installed?
- Can you post the complete path to the file? the name itself seems not to be the problem
- Can you access the file using vanilla python and `open(filename)`?
- Did you activate UTF8 encoding?

**Comment by zfarzaneh** [comment]
I have this problem too . plz help me

**Comment by skjerns** [comment]
Okay, can you please answer the questions that I asked above?

**Comment by skjerns** [comment]
You can Google "utf8 support Windows 10" and follow the instructions? 

What is the filename?

**Comment by zfarzaneh** [comment]
My windows supported utf8 .but i get this error . My file name
is S001R04.edf. It is data for eeg signals  that I take it from
physionet.org.

**Comment by skjerns** [comment]
The file itself is corrupt. This is not a problem of `pyedflib` - opening with EDFBrowser will tell you additional details w.r.t that

**Comment by skjerns** [comment]
should be "fixed" now.

try installing the master version via `pip install git+https://github.com/holgern/pyedflib.git`, it should work now that the warning has been removed.

**Comment by zfarzaneh** [comment]
Thanks a lot .it fixed .

**Comment by mbelley** [comment]
Hi,

I have this to with fedora.
does it have a permanent fix? I tryed install from 27 jun comment and didn't fix for me!

thank's

**Comment by skjerns** [comment]
What's the filename and path you are trying to access?

Can you run this in your terminal and report the output `echo $LANG && echo $LC_CTYPE` ?

**Comment by mbelley** [comment]
> * What's the filename and path you are trying to access?
> * Is the file generally open-able by other EDF-readers like EDFBrowser? If yes, can you upload it somewhere and link it here?
> * Can you run this in your terminal and report the output `echo $LANG && echo $LC_CTYPE` ?
> * Is there no other reported error or warning above the current error?

Hi,

thanks for answer.
This is a sleep apnea edf resmed. Maybe there's some garbage in the file? 

filename and path:  "data/20210803_100630_CSL.edf"

file: [https://drive.google.com/file/d/1qtUxfcElwlRVp2fh44SUJjTiERB1_iCH/view?usp=sharing]

$ echo $LANG && echo $LC_CTYPE
en_CA.UTF-8

stack: 
> OSError: File data/20210803_100630_CSL.edf was found but cant be accessed. Make sure it contains no special characters or change your locale to use UTF8.
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.__init__()

pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.open()

pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.check_open_ok()

OSError: data/20210803_100630_CSL.edf: The file is discontinous and cannot be read

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
/tmp/ipykernel_93955/2968901658.py in <module>
      1 from pyedflib import highlevel
      2 
----> 3 signals, signal_headers, header = highlevel.read_edf(file_name)
      4 # print(signal_headers[0]['sample_frequency']) # prints 256

~/.local/share/virtualenvs/my_apnea_lab-Pw-np_4D/lib64/python3.9/site-packages/pyedflib/highlevel.py in read_edf(edf_file, ch_nrs, ch_names, digital, verbose)
    326         not isinstance(ch_names, list): ch_names = [ch_names]
    327 
--> 328     with pyedflib.EdfReader(edf_file) as f:
    329         # see which channels we want to load
    330         available_chs = [ch.upper() for ch in f.getSignalLabels()]

pyedflib/_extensions/_pyedflib.pyx in pyedflib._extensions._pyedflib.CyEdfReader.__init__()

OSError: File data/20210803_100630_CSL.edf was found but cant be accessed. Make sure it contains no special characters or change your locale to use UTF8.

**Comment by skjerns** [comment]
Mhh, I cannot replicate the issue, the file loads fine for me, both on Windows and WSL. 

Are you sure you are using the most up-to-date version of pyedflib? what prints if you write `print(pyedflib.__version__)`

**Comment by mbelley** [comment]
Hi, I got: 0.1.22

**Comment by skjerns** [comment]
yes, that's not the current one. please install the version from master using `pip install git+https://github.com/holgern/pyedflib.git`, newest is 0.1.23. If you run that command and still have the same problem, than you likely have an environment problem, ie. your pip does not install into the correct python environment

**Comment by mbelley** [comment]
Thanks I'll make sure I have this version (need time...) and let you know.

**Comment by sedket** [comment]
> Thanks a lot .it fixed .

Hi. I'm trying to open the same file as you (the S001R04.edf). Was your problem fixed because you have installed the newest version or because you change the UTF8 thingy? Thank you.

**Comment by skjerns** [comment]
have you tried upgrading pip?

`python -m pip install --upgrade pip`
