### ISSUE TITLE
IOError: the file is not EDF(+) or BDF(+) compliant (Label)

### ISSUE THREAD

**Issue by jkuepker** [holgern/pyedflib#19]
I have several files from my CPAP machine that create EDF files.  For some reason, the 'event annotations' file gets the error in the title.

The other files containing high and low resolution data are fine.

Here is more info on my files: http://sleepyhead.sourceforge.net/wiki/index.php/S9_Data_Format

I have attached an EVE file for reference.
[20170705_211539_EVE.edf.zip](https://github.com/holgern/pyedflib/files/1157255/20170705_211539_EVE.edf.zip)

**Comment by holgern** [comment]
I fixed the error output.
The problem is that the edf file is discontinous. At the moment, this cannot be handled by pyedflib

**Comment by rocapp** [comment]
This is still a problem for me with pyedflib 0.1.14... is this supposed to have been fixed?

**Comment by opop08** [comment]
still a problem............

**Comment by striverwheat** [comment]
still a problem

**Comment by skjerns** [comment]
If the file is still in EDF+D format. Currently there is no plan to support EDF+D formats (streaming), and we are limited by the library we are wrapping `edflib`. Try converting from EDF+D to EDF+C.
